/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ffmpeg_jni_VideoDash */

#ifndef _Included_ffmpeg_jni_VideoDash
#define _Included_ffmpeg_jni_VideoDash
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ffmpeg_jni_VideoDash
 * Method:    getVideoDash
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ffmpeg_1jni_VideoDash_getVideoDash
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     ffmpeg_jni_VideoDash
 * Method:    getVideoMp4
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ffmpeg_1jni_VideoDash_getVideoMp4
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
