/*
 * libVideoDash.h
 *
 *  Created on: 1 may. 2019
 *      Author: brad
 */
#include <jni.h>
#ifndef JNI_LIBVIDEODASH_H_
#define JNI_LIBVIDEODASH_H_



/* DO NOT EDIT THIS FILE - it is machine generated */

/* Header for class ffmpeg_jni_VideoDash */

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ffmpeg_jni_VideoDash
 * Method:    getVideoDash
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ffmpeg_1jni_VideoDash_getVideoDash  (JNIEnv *, jobject, jstring,jstring);

static void logging(const char *fmt, ...);
int getVideoDash( const char* inputFileName,const char* outputDir);


#ifdef __cplusplus
}
#endif



#endif /* JNI_LIBVIDEODASH_H_ */
